// src/components/CardDetail.tsx
import React, { useState, useEffect } from 'react';
import useCardsStore from '@/store';
import { Card, Debit } from '@/types/card';
import { CARD_STATUS } from '@/data/constant';
import { Save, Trash2, Plus, X, CreditCard, Calendar, RefreshCcw } from 'lucide-react';

const CardDetail: React.FC = () => {
    const selectedCard = useCardsStore(state => state.selectedCard);
    const saveCardAction = useCardsStore(state => state.saveCard);
    const removeCardAction = useCardsStore(state => state.removeCard);

    // Local state for editing form
    const [formData, setFormData] = useState<Card | null>(null);

    useEffect(() => {
        if (selectedCard) {
            // Deep copy to avoid direct mutation of store state until save
            setFormData(JSON.parse(JSON.stringify(selectedCard)));
        } else {
            setFormData(null);
        }
    }, [selectedCard]);

    if (!formData) return null;

    const isFormValid = !!(
        formData.name?.trim() &&
        formData.holder &&
        formData.period?.start &&
        formData.period?.end
    );

    const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => {
        const { name, value } = e.target;
        setFormData(prev => prev ? ({ ...prev, [name]: value }) : null);
    };

    const handlePeriodChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        const { name, value } = e.target;
        setFormData(prev => prev ? ({
            ...prev,
            period: {
                ...prev.period,
                [name]: value // string format "YYYY-MM-DD" is fine for input type=date
            }
        }) : null);
    };

    // Need to handle Date object vs string for input type="date"
    const formatDateForInput = (date: Date | string) => {
        if (!date) return '';
        const d = new Date(date);
        if (isNaN(d.getTime())) return ''; // Invalid date check
        return d.toISOString().split('T')[0];
    };

    const addMonthlyPayment = () => {
        setFormData(prev => {
            if (!prev) return null;
            return {
                ...prev,
                automaticDebit: [...(prev.automaticDebit || []), { name: '', cost: '' }]
            };
        });
    };

    const deleteMonthlyPayment = (index: number) => {
        setFormData(prev => {
            if (!prev) return null;
            const newDebits = [...(prev.automaticDebit || [])];
            newDebits.splice(index, 1);
            return { ...prev, automaticDebit: newDebits };
        });
    };

    const handlePaymentChange = (index: number, field: keyof Debit, value: string) => {
        setFormData(prev => {
            if (!prev) return null;
            const newDebits = [...(prev.automaticDebit || [])];
            newDebits[index] = { ...newDebits[index], [field]: value };
            return { ...prev, automaticDebit: newDebits };
        });
    };

    const saveCard = async () => {
        if (!formData || !isFormValid) return;

        const cardName = formData.name || '새 카드';
        if (window.confirm(`${cardName}을(를) 저장하시겠습니까?`)) {
            const savingData = {
                ...formData,
                period: {
                    start: new Date(formData.period.start),
                    end: new Date(formData.period.end)
                }
            };
            await saveCardAction(savingData);
            // alert only if needed, better to just close or show toast
            // alert(`${cardName}이(가) 성공적으로 저장되었습니다.`);
        }
    };

    const deleteCard = async () => {
        const cardName = formData.name || '카드';
        if (window.confirm(`${cardName}을(를) 삭제하시겠습니까? 이 작업은 되돌릴 수 없습니다.`)) {
            if (formData.id) {
                await removeCardAction(formData.id);
            }
        }
    };

    return (
        <div className="flex flex-col h-full bg-[#18181b]">
            <div className="flex-1 overflow-y-auto p-5 sm:p-6 space-y-8 custom-scrollbar">
                {/* Basic Info Section */}
                <div className="space-y-4">
                    <div className="flex items-center gap-2 pb-2 border-b border-white/5">
                        <CreditCard size={16} className="text-indigo-400" />
                        <h4 className="text-sm font-bold text-gray-400 uppercase tracking-wider">기본 정보</h4>
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
                        <div className="space-y-1.5 col-span-2">
                            <label className="text-xs font-semibold text-gray-500 ml-1">카드 이름</label>
                            <input
                                name="name"
                                value={formData.name}
                                onChange={handleInputChange}
                                className="w-full bg-black/20 border border-white/10 rounded-xl px-4 py-2.5 text-sm text-white placeholder-gray-600 focus:outline-none focus:ring-2 focus:ring-indigo-500/50 focus:border-transparent transition-all"
                                placeholder="카드 이름을 입력하세요"
                            />
                        </div>

                        <div className="space-y-1.5">
                            <label className="text-xs font-semibold text-gray-500 ml-1">사용자</label>
                            <div className="relative">
                                <select
                                    name="holder"
                                    value={formData.holder}
                                    onChange={handleInputChange}
                                    className="w-full appearance-none bg-black/20 border border-white/10 rounded-xl px-4 py-2.5 text-sm text-white focus:outline-none focus:ring-2 focus:ring-indigo-500/50 focus:border-transparent transition-all cursor-pointer"
                                >
                                    <option value="conan">Conan</option>
                                    <option value="chaeji">Chaeji</option>
                                </select>
                                <div className="absolute inset-y-0 right-0 flex items-center px-3 pointer-events-none text-gray-500">
                                    <svg className="w-4 h-4 fill-current" viewBox="0 0 20 20"><path d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clipRule="evenodd" fillRule="evenodd"></path></svg>
                                </div>
                            </div>
                        </div>

                        <div className="space-y-1.5">
                            <label className="text-xs font-semibold text-gray-500 ml-1">카드 상태</label>
                            <div className="relative">
                                <select
                                    name="status"
                                    value={formData.status}
                                    onChange={handleInputChange}
                                    className="w-full appearance-none bg-black/20 border border-white/10 rounded-xl px-4 py-2.5 text-sm text-white focus:outline-none focus:ring-2 focus:ring-indigo-500/50 focus:border-transparent transition-all cursor-pointer"
                                >
                                    <option value={CARD_STATUS.USING}>사용중</option>
                                    <option value={CARD_STATUS.KEEPING}>보관중</option>
                                    <option value={CARD_STATUS.TERMINATED}>해지됨</option>
                                </select>
                                <div className="absolute inset-y-0 right-0 flex items-center px-3 pointer-events-none text-gray-500">
                                    <svg className="w-4 h-4 fill-current" viewBox="0 0 20 20"><path d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clipRule="evenodd" fillRule="evenodd"></path></svg>
                                </div>
                            </div>
                        </div>

                        <div className="space-y-1.5">
                            <label className="text-xs font-semibold text-gray-500 ml-1">결제 은행</label>
                            <input
                                name="depositBank"
                                value={formData.depositBank}
                                onChange={handleInputChange}
                                className="w-full bg-black/20 border border-white/10 rounded-xl px-4 py-2.5 text-sm text-white placeholder-gray-600 focus:outline-none focus:ring-2 focus:ring-indigo-500/50 focus:border-transparent transition-all"
                                placeholder="예: 신한은행"
                            />
                        </div>

                        <div className="space-y-1.5">
                            <label className="text-xs font-semibold text-gray-500 ml-1">연회비</label>
                            <input
                                name="annualFee"
                                value={formData.annualFee}
                                onChange={handleInputChange}
                                inputMode="numeric"
                                className="w-full bg-black/20 border border-white/10 rounded-xl px-4 py-2.5 text-sm text-white placeholder-gray-600 focus:outline-none focus:ring-2 focus:ring-indigo-500/50 focus:border-transparent transition-all"
                                placeholder="0"
                            />
                        </div>

                        <div className="space-y-1.5 col-span-2 md:col-span-1">
                            <label className="text-xs font-semibold text-gray-500 ml-1">월 사용금액</label>
                            <input
                                name="monthlyUsage"
                                value={formData.monthlyUsage}
                                onChange={handleInputChange}
                                inputMode="numeric"
                                className="w-full bg-black/20 border border-white/10 rounded-xl px-4 py-2.5 text-sm text-white placeholder-gray-600 focus:outline-none focus:ring-2 focus:ring-indigo-500/50 focus:border-transparent transition-all"
                                placeholder="0"
                            />
                        </div>
                    </div>
                </div>

                {/* Period Section */}
                <div className="space-y-4">
                    <div className="flex items-center gap-2 pb-2 border-b border-white/5">
                        <Calendar size={16} className="text-indigo-400" />
                        <h4 className="text-sm font-bold text-gray-400 uppercase tracking-wider">사용 기간</h4>
                    </div>
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
                        <div className="space-y-1.5">
                            <label className="text-xs font-semibold text-gray-500 ml-1">시작일</label>
                            <input
                                type="date"
                                name="start"
                                value={formatDateForInput(formData.period.start)}
                                onChange={handlePeriodChange}
                                className="w-full bg-black/20 border border-white/10 rounded-xl px-4 py-2.5 text-sm text-white focus:outline-none focus:ring-2 focus:ring-indigo-500/50 focus:border-transparent transition-all [color-scheme:dark]"
                            />
                        </div>
                        <div className="space-y-1.5">
                            <label className="text-xs font-semibold text-gray-500 ml-1">종료일</label>
                            <input
                                type="date"
                                name="end"
                                value={formatDateForInput(formData.period.end)}
                                onChange={handlePeriodChange}
                                className="w-full bg-black/20 border border-white/10 rounded-xl px-4 py-2.5 text-sm text-white focus:outline-none focus:ring-2 focus:ring-indigo-500/50 focus:border-transparent transition-all [color-scheme:dark]"
                            />
                        </div>
                    </div>
                </div>

                {/* Automation Section */}
                <div className="space-y-4">
                    <div className="flex items-center justify-between pb-2 border-b border-white/5">
                        <div className="flex items-center gap-2">
                            <RefreshCcw size={16} className="text-indigo-400" />
                            <h4 className="text-sm font-bold text-gray-400 uppercase tracking-wider">자동 결제</h4>
                        </div>
                        <button
                            type="button"
                            className="flex items-center gap-1.5 px-2.5 py-1 rounded-lg bg-indigo-500/10 text-indigo-400 hover:bg-indigo-500/20 text-xs font-medium transition-colors"
                            onClick={addMonthlyPayment}
                        >
                            <Plus size={12} />
                            추가
                        </button>
                    </div>

                    {formData.automaticDebit && formData.automaticDebit.length > 0 ? (
                        <div className="space-y-3">
                            {formData.automaticDebit.map((payment, index) => (
                                <div key={index} className="flex items-start gap-3 bg-white/5 p-3 rounded-xl border border-white/5 group hover:border-white/10 transition-colors">
                                    <div className="flex-1 grid grid-cols-2 gap-3">
                                        <div className="space-y-1">
                                            <label className="text-[10px] font-semibold text-gray-500 ml-1">내용</label>
                                            <input
                                                value={payment.name}
                                                onChange={(e) => handlePaymentChange(index, 'name', e.target.value)}
                                                className="w-full bg-black/20 border border-white/10 rounded-lg px-3 py-2 text-sm text-white focus:outline-none focus:ring-2 focus:ring-indigo-500/50 focus:border-transparent"
                                                placeholder="결제 내용"
                                            />
                                        </div>
                                        <div className="space-y-1">
                                            <label className="text-[10px] font-semibold text-gray-500 ml-1">금액</label>
                                            <input
                                                value={payment.cost}
                                                onChange={(e) => handlePaymentChange(index, 'cost', e.target.value)}
                                                inputMode="numeric"
                                                className="w-full bg-black/20 border border-white/10 rounded-lg px-3 py-2 text-sm text-white focus:outline-none focus:ring-2 focus:ring-indigo-500/50 focus:border-transparent"
                                                placeholder="0"
                                            />
                                        </div>
                                    </div>
                                    <button
                                        type="button"
                                        className="mt-6 p-2 text-gray-500 hover:text-red-400 hover:bg-red-400/10 rounded-lg transition-colors"
                                        onClick={() => deleteMonthlyPayment(index)}
                                    >
                                        <X size={16} />
                                    </button>
                                </div>
                            ))}
                        </div>
                    ) : (
                        <div className="py-8 border border-dashed border-white/10 rounded-xl flex flex-col items-center justify-center text-gray-500 text-sm">
                            <p>등록된 자동 결제가 없습니다.</p>
                        </div>
                    )}
                </div>
            </div>

            {/* Footer / Actions */}
            <div className="p-6 border-t border-white/5 bg-black/20 backdrop-blur-sm flex items-center justify-between gap-4">
                <button
                    type="button"
                    className="flex items-center gap-2 px-4 py-3 rounded-xl text-red-400 hover:bg-red-400/10 text-sm font-medium transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                    onClick={deleteCard}
                    disabled={!formData.id}
                >
                    <Trash2 size={18} />
                    <span className="hidden sm:inline">삭제</span>
                </button>

                <div className="flex items-center gap-3 w-full sm:w-auto">
                    <button
                        type="button"
                        className={`
                            flex-1 sm:flex-none flex items-center justify-center gap-2 px-8 py-3 rounded-xl 
                            text-sm font-bold text-white shadow-lg shadow-indigo-500/20
                            transition-all duration-200
                            ${isFormValid
                                ? 'bg-indigo-600 hover:bg-indigo-500 hover:scale-[1.02] cursor-pointer'
                                : 'bg-gray-700 cursor-not-allowed opacity-50'}
                        `}
                        onClick={saveCard}
                        disabled={!isFormValid}
                    >
                        <Save size={18} />
                        저장
                    </button>
                </div>
            </div>
        </div>
    );
};

export default CardDetail;

// src/components/CardDetail.vue
<template>
    <div class="card-detail" v-if="card">
        <div class="detail-form">
            <!-- Basic Information -->
            <div class="form-section">
                <h4 class="section-title">기본 정보</h4>
                <div class="form-grid">
                    <div class="form-field">
                        <label class="field-label">카드 이름</label>
                        <input 
                            v-model="card.name" 
                            class="field-input"
                            placeholder="카드 이름을 입력하세요"
                        />
                    </div>
                    <div class="form-field">
                        <label class="field-label">사용자</label>
                        <select v-model="card.holder" class="field-select">
                            <option value="conan">Conan</option>
                            <option value="chaeji">Chaeji</option>
                        </select>
                    </div>
                    <div class="form-field">
                        <label class="field-label">결제 은행</label>
                        <input 
                            v-model="card.deposit_bank" 
                            class="field-input"
                            placeholder="결제 은행을 입력하세요"
                        />
                    </div>
                    <div class="form-field">
                        <label class="field-label">연회비</label>
                        <input 
                            v-model="card.annual_fee" 
                            class="field-input"
                            type="number"
                            placeholder="0"
                        />
                    </div>
                    <div class="form-field">
                        <label class="field-label">월 사용금액</label>
                        <input 
                            v-model="card.monthly_usage" 
                            class="field-input"
                            type="number"
                            placeholder="0"
                        />
                    </div>
                    <div class="form-field">
                        <label class="field-label">카드 상태</label>
                        <select v-model="card.status" class="field-select">
                            <option value="using">사용중</option>
                            <option value="keeping">보관중</option>
                            <option value="terminated">해지됨</option>
                        </select>
                    </div>
                </div>
            </div>

            <!-- Usage Period -->
            <div class="form-section">
                <h4 class="section-title">사용 기간</h4>
                <div class="form-grid">
                    <div class="form-field">
                        <label class="field-label">시작일</label>
                        <input 
                            type="date" 
                            v-model="card.period_start" 
                            class="field-input"
                        />
                    </div>
                    <div class="form-field">
                        <label class="field-label">종료일</label>
                        <input 
                            type="date" 
                            v-model="card.period_end" 
                            class="field-input"
                        />
                    </div>
                </div>
            </div>

            <!-- Auto Payments -->
            <div class="form-section">
                <div class="section-header">
                    <h4 class="section-title">자동 결제</h4>
                    <button 
                        type="button" 
                        class="add-button"
                        @click="addMonthlyPayment"
                    >
                        <i class="add-icon">+</i>
                        추가
                    </button>
                </div>
                <div class="auto-payments-list" v-if="card.debits && card.debits.length > 0">
                    <div 
                        v-for="(payment, index) in card.debits" 
                        :key="index"
                        class="payment-item"
                    >
                        <div class="payment-fields">
                            <div class="form-field">
                                <label class="field-label">내용</label>
                                <input 
                                    v-model="payment.name" 
                                    class="field-input"
                                    placeholder="결제 내용"
                                />
                            </div>
                            <div class="form-field">
                                <label class="field-label">금액</label>
                                <input 
                                    v-model="payment.cost" 
                                    class="field-input"
                                    type="number"
                                    placeholder="0"
                                />
                            </div>
                        </div>
                        <button 
                            type="button" 
                            class="remove-button"
                            @click="deleteMonthlyPayment(payment)"
                        >
                            <i class="remove-icon">×</i>
                        </button>
                    </div>
                </div>
                <div v-else class="empty-state">
                    <p>등록된 자동 결제가 없습니다.</p>
                </div>
            </div>
        </div>

        <!-- Action Buttons -->
        <div class="action-buttons">
            <button 
                type="button" 
                class="save-button"
                @click="saveCard"
                :disabled="!isFormValid"
            >
                <i class="save-icon">💾</i>
                저장
            </button>
            <button 
                type="button" 
                class="delete-button"
                @click="deleteCard"
                :disabled="!card.id"
            >
                <i class="delete-icon">🗑️</i>
                삭제
            </button>
        </div>
    </div>
</template>

<script lang="ts">
import { Vue, Component } from 'vue-property-decorator'
import { CARD_STATUS } from '@/assets/constant'

interface Card {
    id?: string
    name: string
    holder: 'conan' | 'chaeji'
    deposit_bank: string
    annual_fee: string
    monthly_usage: string
    period_start: string
    period_end: string
    status: string
    debits?: Array<{
        name: string
        cost: string
    }>
}

interface MonthlyPayment {
    name: string
    cost: string
}

@Component
export default class CardDetail extends Vue {
    get card(): Card | null {
        return this.$store.getters.selectedCard || null
    }

    get isFormValid(): boolean {
        if (!this.card) return false
        
        return !!(
            this.card.name?.trim() &&
            this.card.holder &&
            this.card.period_start &&
            this.card.period_end
        )
    }

    getStatusText(status: string): string {
        const statusMap: Record<string, string> = {
            [CARD_STATUS.USING]: '사용중',
            [CARD_STATUS.KEEPING]: '보관중',
            [CARD_STATUS.TERMINATED]: '해지됨'
        }
        
        return statusMap[status] || status
    }

    addMonthlyPayment(): void {
        if (!this.card) return
        
        this.$store.commit('addMonthlyPayment')
        this.$forceUpdate()
    }

    deleteMonthlyPayment(monthlyPayment: MonthlyPayment): void {
        if (!this.card) return
        
        this.$store.commit('deleteMonthlyPayment', monthlyPayment)
    }

    async saveCard(): Promise<void> {
        if (!this.card || !this.isFormValid) return
        
        const cardName = this.card.name || '새 카드'
        const confirmed = confirm(`${cardName}을(를) 저장하시겠습니까?`)
        
        if (confirmed) {
            try {
                await this.$store.dispatch('save')
                alert(`${cardName}이(가) 성공적으로 저장되었습니다.`)
                this.$emit('card-saved', this.card)
            } catch (error) {
                console.error('Failed to save card:', error)
                alert('카드 저장에 실패했습니다.')
            }
        }
    }

    async deleteCard(): Promise<void> {
        if (!this.card || !this.card.id) return
        
        const cardName = this.card.name || '카드'
        const confirmed = confirm(`${cardName}을(를) 삭제하시겠습니까? 이 작업은 되돌릴 수 없습니다.`)
        
        if (confirmed) {
            try {
                await this.$store.dispatch('delete', this.card.id)
                alert(`${cardName}이(가) 성공적으로 삭제되었습니다.`)
                this.$emit('card-deleted', this.card)
            } catch (error) {
                console.error('Failed to delete card:', error)
                alert('카드 삭제에 실패했습니다.')
            }
        }
    }

    formatCurrency(value: string): string {
        const num = parseFloat(value)
        if (isNaN(num)) return '0'
        return num.toLocaleString('ko-KR')
    }
}
</script>

<style scoped lang="scss">
.card-detail {
    display: flex;
    flex-direction: column;
    height: 100%;
    background: #2d2d2d;
    border-radius: 12px;
    overflow: hidden;
}


.detail-form {
    flex: 1;
    padding: 1rem;
    overflow-y: auto;
}

.form-section {
    margin-bottom: 1.5rem;

    &:last-child {
        margin-bottom: 0;
    }

    .section-title {
        margin: 0 0 0.75rem 0;
        font-size: 1rem;
        font-weight: 600;
        color: #e0e0e0;
        padding-bottom: 0.3rem;
        border-bottom: 2px solid #404040;
    }

    .section-header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin-bottom: 0.75rem;

        .section-title {
            margin: 0;
            border: none;
            padding: 0;
        }
    }
}

.form-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
    gap: 0.75rem;
}

.form-field {
    display: flex;
    flex-direction: column;
    gap: 0.3rem;

    .field-label {
        font-size: 0.8rem;
        font-weight: 600;
        color: #b0b0b0;
        margin: 0;
    }

    .field-input,
    .field-select {
        padding: 0.5rem;
        border: 2px solid #555;
        border-radius: 6px;
        font-size: 0.8rem;
        transition: all 0.3s ease;
        background: #3a3a3a;
        color: #e0e0e0;

        &:focus {
            outline: none;
            border-color: #667eea;
            box-shadow: 0 0 0 3px rgba(102, 126, 234, 0.1);
        }

        &::placeholder {
            color: #888;
        }
    }

    .field-select {
        cursor: pointer;
    }
}

.add-button {
    display: flex;
    align-items: center;
    gap: 0.4rem;
    padding: 0.4rem 0.8rem;
    background: #28a745;
    color: white;
    border: none;
    border-radius: 5px;
    font-size: 0.8rem;
    font-weight: 500;
    cursor: pointer;
    transition: all 0.3s ease;

    &:hover {
        background: #218838;
        transform: translateY(-1px);
        box-shadow: 0 4px 12px rgba(40, 167, 69, 0.3);
    }

    .add-icon {
        font-size: 1rem;
        font-weight: bold;
    }
}

.auto-payments-list {
    display: flex;
    flex-direction: column;
    gap: 0.75rem;
}

.payment-item {
    display: flex;
    align-items: flex-end;
    gap: 0.75rem;
    padding: 0.75rem;
    background: #3a3a3a;
    border-radius: 6px;
    border: 1px solid #555;

    .payment-fields {
        flex: 1;
        display: grid;
        grid-template-columns: 1fr 1fr;
        gap: 0.75rem;
    }

    .remove-button {
        width: 32px;
        height: 32px;
        background: #dc3545;
        color: white;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        transition: all 0.3s ease;
        display: flex;
        align-items: center;
        justify-content: center;

        &:hover {
            background: #c82333;
            transform: scale(1.05);
        }

        .remove-icon {
            font-size: 1rem;
            font-weight: bold;
        }
    }
}

.empty-state {
    text-align: center;
    padding: 1.5rem;
    color: #888;
    font-style: italic;
    font-size: 0.9rem;
}

.action-buttons {
    display: flex;
    gap: 0.75rem;
    padding: 1rem;
    background: #3a3a3a;
    border-top: 1px solid #555;
}

.save-button,
.delete-button {
    flex: 1;
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 0.4rem;
    padding: 0.6rem 1.2rem;
    border: none;
    border-radius: 6px;
    font-size: 0.9rem;
    font-weight: 600;
    cursor: pointer;
    transition: all 0.3s ease;

    &:disabled {
        opacity: 0.6;
        cursor: not-allowed;
        transform: none !important;
    }
}

.save-button {
    background: #007bff;
    color: white;

    &:hover:not(:disabled) {
        background: #0056b3;
        transform: translateY(-1px);
    }
}

.delete-button {
    background: #dc3545;
    color: white;

    &:hover:not(:disabled) {
        background: #c82333;
        transform: translateY(-1px);
    }
}

.save-icon,
.delete-icon {
    font-size: 1.1rem;
}

// Responsive design
@media (max-width: 768px) {
    .detail-header {
        padding: 1rem;
        flex-direction: column;
        gap: 1rem;
        text-align: center;

        .card-title {
            font-size: 1.3rem;
        }
    }

    .detail-form {
        padding: 1rem;
    }

    .form-grid {
        grid-template-columns: 1fr;
        gap: 0.75rem;
    }

    .payment-item {
        flex-direction: column;
        align-items: stretch;

        .payment-fields {
            grid-template-columns: 1fr;
        }

        .remove-button {
            align-self: flex-end;
            width: auto;
            padding: 0.5rem 1rem;
        }
    }

    .action-buttons {
        flex-direction: column;
        gap: 0.75rem;
    }
}

@media (max-width: 480px) {
    .detail-header {
        .card-title {
            font-size: 1.2rem;
        }

        .card-status-badge {
            font-size: 0.8rem;
            padding: 0.4rem 0.8rem;
        }
    }

    .form-field {
        .field-input,
        .field-select {
            padding: 0.6rem;
            font-size: 0.85rem;
        }
    }
}
</style>
